### PR TITLE
Tinygl: optimise scissorpixel

### PR DESCRIPTION
**Pull request by vpelletier**
And avoid calling it altogether when possible.

Note: contains #1266 as it would otherwise conflict, I don't know how to do otherwise to still propose these patches.

### CODE REVIEW

**Comment by bgK** [comment]
:+1: (for the changes new in this patchset)

**Comment by vpelletier** [comment]
Is there anything blocking this PR ?

**Comment by aquadran** [comment]
hmm, it contain changes from other PR

**Comment by vpelletier** [comment]
True. Also, i've been working on zdirtyrect lately (not sure anything conclusive will come out of it yet) and I changed my mind on how scissorPixel should be optimised: zdirtyrect makes extensive use of it, and I only recently realised it is actually mostly dead code so far (it uses whole-screen blits unless enabled specifically, and it's not enabled).
And when enabling, performance becomes abysmal just because of the modulo in scissorPixel. So I made all callers know (and provide) the 2D coordinates to scissorPixel, so it can directly compare without any operation - and as a result, I think it is overkill to control just 4 comparisons with a with a template-level flag.

**Comment by vpelletier** [comment]
I rebased this pull-request over master, and pushed the optimisation of `scissorPixel` further, to prepare for enabling dirty rectangle mechanism by default (...which may still require a lot of work, but I'm not sure where to discuss it).

**Pull request merged**
