### PR TITLE
GRAPHICS: Do not use SDL_WINDOW_RESIZEABLE

### PR DESCRIPTION
**Pull request by raziel-**
See also the forums thread for further information
https://forums.residualvm.org/viewtopic.php?f=1&t=766

### CODE REVIEW

**Comment by raziel-** [comment]
Followup to @Botje 
https://forums.residualvm.org/viewtopic.php?f=1&t=766#p4323

**Comment by bgK** [comment]
Please leave `SDL_WINDOW_RESIZEABLE`, the window is intended to be resizeable.

What needs to be done here is to make the window not resizeable when the game does not support arbitrary resolutions and the platform does not support rendering to a framebuffer.

**Comment by raziel-** [comment]
That is beyond my capabilities, sorry

**Comment by bgK** [comment]
I've pushed a change to your branch to implement that rule. Would you mind testing it on AmigaOS ?

**Comment by raziel-** [comment]
@bkK

With your change it still works on AmigaOS4.
I get a window missing the resize gadget.

**Comment by bgK** [comment]
Ok, let's merge it then.

**Pull request merged**
