### PR TITLE
GRIM: Make patch file reads alignment safe

### PR DESCRIPTION
**Pull request by joostp**
This changes the unsafe pointer reads/writes to use READ_UINT32() / WRITE_UINT32().
Since there are no 64-bit versions of these functions, the 64-bit codepath was eliminated.

I don't know how big the performance gains here are for splitting this into 4-byte chunks, the code would definitely be more readable if it were changed into a simple 1-byte xor...

### CODE REVIEW

**Comment by aquadran** [comment]
@YakBizzarro: can you comment that part of 32/64 bit, why is that?

**Comment by YakBizzarro** [comment]
My idea was to use the larger register size to reduce the number of the iterations. Maybe it's only a premature optimization, since I never looked at the resulting assembly or benchmarked it. Anyway, keep in mind that a very large part of the file that need to be patched, must pass through that cycle. Untouched part of a file are just xored with zero, which are greatly compressed by gzip, so the number of cycles is quite high

**Comment by aquadran** [comment]
I'm not sure if it's worth. At this point aligned is more important, I'm thinking about to merge it. We can bring this back (after merge 64 macros) if it's indeed faster, if not it make no sense at all to complicate code.

**Comment by YakBizzarro** [comment]
Ok. I'll reintroduce the 64bit codepath if I can prove that it's a real optimization ;)

**Pull request merged**
