### PR TITLE
GRIM: SHADERS: Enable GL_BLEND when texture has transparency.

### PR DESCRIPTION
**Pull request by vpelletier**
Fixes, likely among others, the tie rope in set "al".

### CODE REVIEW

**Comment by bgK** [comment]
The OpenGL renderer seems to do alpha testing. Not sure if doing blending instead has much of an impact.

**Comment by vpelletier** [comment]
It does fix the tie rope for me, at least. No idea if it is the right way, though.

**Comment by vpelletier** [comment]
I just noticed I can see through Glotis' mouth in set "ga". I didn't check if it is due to this commit.

**Comment by bgK** [comment]
The alpha test approach seems to get both the rope and Glotis right.
https://gist.github.com/bgK/0308b600a10359cb1489

**Comment by vpelletier** [comment]
I confirm your patch works better. Should I close this pull request and let you push your patch ?

**Comment by bgK** [comment]
Done in https://github.com/residualvm/residualvm/commit/d1b72c7975b6697b47bb7bc35a73d3b20d89af26

**Pull request closed without merging**
