### PR TITLE
WIP: ANDROID: Rewrite control schemes

### PR DESCRIPTION
**Pull request by Botje**
This PR is a revised version of #841.
The TOUCH_BACKEND define has been superceded in favor of ENABLE_TOUCH,
which should be enabled on a per-backend basis in the configure script.

With this patchset, every engine can supply its own input handler.
I have extracted the baked-in GRIM/EMI controls into such a handler.

I've also removed a lot of cruft from the Android backend, hopefully
much of it can be reused for the iOS backend.

Comments welcome!

### CODE REVIEW

**Comment by Botje** [comment]
I cleaned up the code and removed the last hard-coded android code, but I'm not done yet for this PR.
Final plans:
- Implement a simple gamepad layout for grim and EMI
- Add touch controls for Myst3

**Comment by Botje** [comment]
Okay, this was the last serious rebase, I think. Comments welcome!

**Comment by aquadran** [comment]
let's bring this back. in general I'm fine to merge this. let see after rebase to current code

**Comment by aquadran** [comment]
as it's obsolete in current form and solution on scummvm will be more generic

**Pull request closed without merging**
